# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5BWww5mBHocr8uVPhWCcywtPpIO4jyB
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans

st.set_page_config(page_title="Iris Clustering", page_icon="🌸")
st.title("🌸 Iris Flower Clustering using K-Means")

# Load Data
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)[
    ['petal length (cm)', 'petal width (cm)']
]

st.subheader("Dataset")
st.dataframe(df.head())

# Original Scatter Plot
fig, ax = plt.subplots()
ax.scatter(df['petal length (cm)'], df['petal width (cm)'])
ax.set_xlabel("Petal Length")
ax.set_ylabel("Petal Width")
st.pyplot(fig)

# Scaling
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

# Elbow Method
sse = []
for i in range(1, 11):
    km = KMeans(n_clusters=i, random_state=42)
    km.fit(df_scaled)
    sse.append(km.inertia_)

fig, ax = plt.subplots()
ax.plot(range(1, 11), sse, marker='o')
ax.set_title("Elbow Method")
ax.set_xlabel("K")
ax.set_ylabel("SSE")
st.pyplot(fig)

# K Selection
k = st.slider("Select K", 2, 10, 3)

# Clustering
model = KMeans(n_clusters=k, random_state=42)
df_scaled["Cluster"] = model.fit_predict(df_scaled)

# Cluster Plot
fig, ax = plt.subplots()

for i in range(k):
    d = df_scaled[df_scaled["Cluster"] == i]
    ax.scatter(d['petal length (cm)'],
               d['petal width (cm)'],
               label=f'Cluster {i}')

ax.scatter(model.cluster_centers_[:,0],
           model.cluster_centers_[:,1],
           marker='*',
           s=200,
           color='black',
           label='Centroids')

ax.legend()
st.pyplot(fig)

# Result
result = df.copy()
result["Species"] = iris.target_names[iris.target]
result["Cluster"] = df_scaled["Cluster"]

st.subheader("Clustered Data")
st.dataframe(result)

st.subheader("Comparison")
st.write(pd.crosstab(result["Species"], result["Cluster"]))

# Download
st.download_button(
    "Download CSV",
    result.to_csv(index=False),
    "iris_clustered_data.csv",
    "text/csv"
)
